/**
 * Integration tests for split_body_by_bends using real STEP fixtures.
 *
 * Requires:
 *   1. A built geometry_addon.node (cpp/build/Release/ or cpp/build-vcpkg/Debug/)
 *   2. STEP fixtures generated by `generate_fixtures` (cpp/tests/fixtures/)
 *
 * Tests are skipped silently when the addon or fixtures are absent.
 */

import { describe, expect, it, beforeAll } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';

import { dispatchTool } from '../../src/mcp/tools';
import { loadConfig } from '../../src/config/loader';

// ─── Addon detection ──────────────────────────────────────────────────────────

function findAddonPath(): string | undefined {
  // Prefer Release (kept current by `cmake-js build`). Fall back to Debug only
  // if Release is missing. Prior ordering checked Debug first and silently
  // used stale binaries when the developer rebuilt Release.
  const candidates = [
    path.resolve(__dirname, '../../../cpp/build/Release/geometry_addon.node'),
    path.resolve(__dirname, '../../../cpp/build-vcpkg/Debug/geometry_addon.node'),
    path.resolve(__dirname, '../../../cpp/build/Debug/geometry_addon.node'),
  ];
  return candidates.find(p => fs.existsSync(p));
}

function findFixture(filename: string): string | undefined {
  const fixturesDir = path.resolve(__dirname, '../../../cpp/tests/fixtures');
  const fp = path.join(fixturesDir, filename);
  return fs.existsSync(fp) ? fp : undefined;
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('split_body_by_bends integration', () => {
  console.log('split_body_by_bends integration tests starting...');
  let addonAvailable = false;
  const configPath = path.resolve(__dirname, '../../config/config.yaml');

  beforeAll(() => {
    const addonPath = findAddonPath();
    if (addonPath) {
      process.env['GEOMETRY_ADDON_PATH'] = addonPath;
      addonAvailable = true;
    }
  });

  it('hollow cube → thin_solid mode, 6 panels, 0 protrusions', async () => {
    if (!addonAvailable) return;
console.log('split_body_by_bends.hollow cube tests starting...');
  
    const fixturePath = findFixture('hollow_cube.stp');
    if (!fixturePath) {
      console.warn('hollow_cube.stp not found — run generate_fixtures first');
      return;
    }

    const config = loadConfig(configPath);

    const clean = await dispatchTool('clean_geometry', { file_path: fixturePath }, config) as any;
    expect(clean.solid_id).toBeDefined();

    const result = await dispatchTool('split_body_by_bends', {
      part_id: clean.solid_id,
      angle_threshold_deg: 45,
      max_thickness_mm: 5.0,
    }, config) as any;

    expect(result.detected_mode).toBe('thin_solid');
    expect(result.panel_count).toBe(6);
    expect(result.protrusion_count).toBe(0);
    expect(result.panel_ids).toHaveLength(6);
    expect(result.rollback_token).toBeDefined();
  });

  
  it('two hollow cubes → thin_solid mode, 12 panels, 4 bridge flanges', async () => {
    if (!addonAvailable) return;
console.log('split_body_by_bends.two hollow cubes tests starting...');

    const fixturePath = findFixture('testcube.step');
    if (!fixturePath) {
      console.warn('testcube.step not found — run generate_fixtures first');
      return;
    }

    const config = loadConfig(configPath);

    const clean = await dispatchTool('clean_geometry', { file_path: fixturePath }, config) as any;
    expect(clean.solid_id).toBeDefined();

    let result: any;
    try {
      result = await dispatchTool('split_body_by_bends', {
        part_id: clean.solid_id,
        angle_threshold_deg: 45,
        max_thickness_mm: 2.0,
        max_recursion_depth: 2,
      }, config);
      // Debug output
      // eslint-disable-next-line no-console
      console.log('split_body_by_bends result:', JSON.stringify(result, null, 2));
    } catch (err) {
      // eslint-disable-next-line no-console
      console.error('split_body_by_bends error:', err);
      throw err;
    }

    expect(result.detected_mode).toBe('thin_solid');
    expect(result.panel_count).toBe(12);
    // testcube has 4 real bridge flanges connecting the inner and outer cubes.
    // Option-3 in detectProtrusions detects these as anti-parallel interior
    // face-group pairs (thin slabs) using bounded-box extraction.
    expect(result.protrusion_count).toBe(4);
    expect(result.panel_ids).toHaveLength(12);
    expect(result.rollback_token).toBeDefined();

    // Verify manufacturing graphs were created for ALL panels AND protrusions.
    // created_parts must contain 12 panels + 4 protrusions = 16 entries.
    expect(result.created_parts).toHaveLength(16);
    // Every protrusion shell must have its own manufacturing graph entry.
    const createdPartIds: string[] = result.created_parts.map((cp: any) => cp.part_id);
    for (const protId of result.protrusion_ids) {
      expect(createdPartIds, `protrusion ${protId} must have a manufacturing graph`).toContain(protId);
    }
  });

  // ── Diagnostic: protrusion bboxes must be local features, not full panels ──
  //
  // Regression test for the bug where `split_body_by_bends` on testcube.step
  // returns protrusion shells that are actually outer-cube panel slabs. The
  // root cause is half-space extraction at an interior host plane over-
  // capturing everything beyond the plane.
  //
  // Validation: each protrusion's AABB volume must be MUCH smaller than the
  // largest panel's AABB volume. A real protrusion (tab, boss, flange) is a
  // localized feature and should not approach panel dimensions.
  it('testcube: protrusion bboxes are local features, not panel-sized', async () => {
    if (!addonAvailable) return;

    const fixturePath = findFixture('testcube.step');
    if (!fixturePath) {
      console.warn('testcube.step not found — skipping');
      return;
    }
    const config = loadConfig(configPath);

    const clean = await dispatchTool('clean_geometry', { file_path: fixturePath }, config) as { solid_id: string };
    const result = await dispatchTool('split_body_by_bends', {
      part_id: clean.solid_id,
      angle_threshold_deg: 45,
      max_thickness_mm: 2.0,
      max_recursion_depth: 2,
    }, config) as {
      panel_count: number;
      protrusion_count: number;
      panel_bboxes: Array<{ x_min: number; y_min: number; z_min: number; x_max: number; y_max: number; z_max: number }>;
      protrusion_bboxes: Array<{ x_min: number; y_min: number; z_min: number; x_max: number; y_max: number; z_max: number }>;
    };
    expect(result.panel_count).toBe(12);
    expect(result.protrusion_count).toBe(4);

    const bboxVolume = (b: { x_min: number; y_min: number; z_min: number; x_max: number; y_max: number; z_max: number }) =>
      (b.x_max - b.x_min) * (b.y_max - b.y_min) * (b.z_max - b.z_min);
    const maxDim = (b: { x_min: number; y_min: number; z_min: number; x_max: number; y_max: number; z_max: number }) =>
      Math.max(b.x_max - b.x_min, b.y_max - b.y_min, b.z_max - b.z_min);

    const panelVolumes = result.panel_bboxes.map(bboxVolume);
    const largestPanelVolume = Math.max(...panelVolumes);
    const largestPanelMaxDim = Math.max(...result.panel_bboxes.map(maxDim));

    // Log diagnostic info so failures are easy to interpret.
    // eslint-disable-next-line no-console
    console.log('panel bbox volumes (sorted desc):',
      [...panelVolumes].sort((a, b) => b - a).map(v => v.toFixed(0)));
    // eslint-disable-next-line no-console
    console.log('protrusion bbox volumes (sorted desc):',
      result.protrusion_bboxes.map(bboxVolume).sort((a, b) => b - a).map(v => v.toFixed(0)));
    // eslint-disable-next-line no-console
    console.log('protrusion bbox max-dimensions:',
      result.protrusion_bboxes.map(maxDim).map(d => d.toFixed(1)));
    // eslint-disable-next-line no-console
    console.log('largest panel volume:', largestPanelVolume.toFixed(0),
                'largest panel max-dim:', largestPanelMaxDim.toFixed(1));

    // Print each protrusion's AABB coordinates so we can identify what face
    // and what extraction direction produced it.
    const fmtBbox = (b: { x_min: number; y_min: number; z_min: number; x_max: number; y_max: number; z_max: number }) =>
      `x[${b.x_min.toFixed(1)}..${b.x_max.toFixed(1)}]` +
      ` y[${b.y_min.toFixed(1)}..${b.y_max.toFixed(1)}]` +
      ` z[${b.z_min.toFixed(1)}..${b.z_max.toFixed(1)}]` +
      ` dims=${(b.x_max - b.x_min).toFixed(1)}×${(b.y_max - b.y_min).toFixed(1)}×${(b.z_max - b.z_min).toFixed(1)}`;
    // eslint-disable-next-line no-console
    console.log('protrusion bbox coords:');
    result.protrusion_bboxes.forEach((b, i) => {
      // eslint-disable-next-line no-console
      console.log(`  [${i}] ${fmtBbox(b)}`);
    });
    // eslint-disable-next-line no-console
    console.log('panel bbox coords:');
    result.panel_bboxes.forEach((b, i) => {
      // eslint-disable-next-line no-console
      console.log(`  [${i}] ${fmtBbox(b)}`);
    });

    // Each protrusion must be a localized feature, not panel-sized.
    // Volume cap (25%) catches plate-style misdetections where a half-space
    // cut over-extracts an entire wall slab. The max-dimension cap (85%)
    // accommodates bridge flanges that legitimately span the inner cube's
    // full height (150 mm of the 200 mm outer assembly, ~75%) plus a small
    // boolean-extraction bleed margin — anything beyond 85% indicates the
    // extraction has wrapped around the outer hull.
    for (let i = 0; i < result.protrusion_bboxes.length; i++) {
      const pVol = bboxVolume(result.protrusion_bboxes[i]);
      const pMaxDim = maxDim(result.protrusion_bboxes[i]);
      expect(pVol, `protrusion ${i} volume ${pVol.toFixed(0)} should be < 25% of largest panel volume ${largestPanelVolume.toFixed(0)}`)
        .toBeLessThan(largestPanelVolume * 0.25);
      expect(pMaxDim, `protrusion ${i} max-dimension ${pMaxDim.toFixed(1)} should be < 85% of largest panel max-dimension ${largestPanelMaxDim.toFixed(1)}`)
        .toBeLessThan(largestPanelMaxDim * 0.85);
    }
  });

/*
    it('Braai fixture → split by bends, part count reasonable', async () => {
      if (!addonAvailable) return;
console.log('split_body_by_bends.Braai fixture tests starting...');

      // Try both possible locations for the Braai fixture
      const fixturePath = findFixture('braai.step');
      if (!fixturePath) {
        console.warn('braai.step not found — ensure the Braai fixture is available');
        return;
      }

      const config = loadConfig(configPath);

      let clean: any;
      let result: any;
      try {
        clean = await dispatchTool('clean_geometry', { file_path: fixturePath }, config);
        expect(clean.solid_id).toBeDefined();

        result = await dispatchTool('split_body_by_bends', {
          part_id: clean.solid_id,
          angle_threshold_deg: 45,
          max_thickness_mm: 5.0,
          max_recursion_depth: 0,
        }, config);
      } catch (err: any) {
        let msg = 'split_body_by_bends failed: ';
        if (err && typeof err === 'object') {
          if ('message' in err) msg += err.message;
          else msg += JSON.stringify(err);
        } else {
          msg += String(err);
        }
        throw new Error(msg);
      }

      expect(result).toBeDefined();
      expect(Array.isArray(result.panel_ids)).toBe(true);
      expect(result.panel_ids.length).toBeGreaterThan(0);
      expect(result.panel_ids.length).toBeLessThanOrEqual(100);

      // Bounding box check using panel_bboxes returned from the C++ layer.
      if (result.panel_bboxes && Array.isArray(result.panel_bboxes) && result.panel_bboxes.length > 0) {
        // Compute the union bbox of all panels as a proxy for the original solid's extent.
        let unionBbox = { ...result.panel_bboxes[0] };
        for (const b of result.panel_bboxes) {
          unionBbox.x_min = Math.min(unionBbox.x_min, b.x_min);
          unionBbox.y_min = Math.min(unionBbox.y_min, b.y_min);
          unionBbox.z_min = Math.min(unionBbox.z_min, b.z_min);
          unionBbox.x_max = Math.max(unionBbox.x_max, b.x_max);
          unionBbox.y_max = Math.max(unionBbox.y_max, b.y_max);
          unionBbox.z_max = Math.max(unionBbox.z_max, b.z_max);
        }
        const unionDiag = Math.sqrt(
          Math.pow(unionBbox.x_max - unionBbox.x_min, 2) +
          Math.pow(unionBbox.y_max - unionBbox.y_min, 2) +
          Math.pow(unionBbox.z_max - unionBbox.z_min, 2)
        );
        // eslint-disable-next-line no-console
        console.log('[Braai Test] Panel union bbox:', unionBbox, `diagonal=${unionDiag.toFixed(1)} mm`);

        for (let i = 0; i < result.panel_bboxes.length; ++i) {
          const b = result.panel_bboxes[i];
          const dx = b.x_max - b.x_min;
          const dy = b.y_max - b.y_min;
          const dz = b.z_max - b.z_min;
          const diag = Math.sqrt(dx * dx + dy * dy + dz * dz);
          // eslint-disable-next-line no-console
          console.log(`[Braai Test] Panel ${i + 1} bbox: x=[${b.x_min.toFixed(1)}, ${b.x_max.toFixed(1)}] y=[${b.y_min.toFixed(1)}, ${b.y_max.toFixed(1)}] z=[${b.z_min.toFixed(1)}, ${b.z_max.toFixed(1)}] diag=${diag.toFixed(1)} mm`);
          const outsideUnion =
            b.x_min < unionBbox.x_min - 1 || b.x_max > unionBbox.x_max + 1 ||
            b.y_min < unionBbox.y_min - 1 || b.y_max > unionBbox.y_max + 1 ||
            b.z_min < unionBbox.z_min - 1 || b.z_max > unionBbox.z_max + 1;
          if (outsideUnion) {
            // eslint-disable-next-line no-console
            console.warn(`[Braai Test] Panel ${i + 1} extends OUTSIDE the union bbox — likely a bad cut!`);
          }
          // A panel whose diagonal is more than 5× the union diagonal is almost certainly wrong
          if (diag > unionDiag * 5) {
            // eslint-disable-next-line no-console
            console.warn(`[Braai Test] Panel ${i + 1} diagonal (${diag.toFixed(1)} mm) is suspiciously large vs union (${unionDiag.toFixed(1)} mm)`);
          }
        }

        if (result.protrusion_bboxes && Array.isArray(result.protrusion_bboxes)) {
          for (let i = 0; i < result.protrusion_bboxes.length; ++i) {
            const b = result.protrusion_bboxes[i];
            const dx = b.x_max - b.x_min;
            const dy = b.y_max - b.y_min;
            const dz = b.z_max - b.z_min;
            const diag = Math.sqrt(dx * dx + dy * dy + dz * dz);
            // eslint-disable-next-line no-console
            console.log(`[Braai Test] Protrusion ${i + 1} bbox: x=[${b.x_min.toFixed(1)}, ${b.x_max.toFixed(1)}] y=[${b.y_min.toFixed(1)}, ${b.y_max.toFixed(1)}] z=[${b.z_min.toFixed(1)}, ${b.z_max.toFixed(1)}] diag=${diag.toFixed(1)} mm`);
          }
        }
      } else {
        // eslint-disable-next-line no-console
        console.warn('[Braai Test] panel_bboxes not returned — rebuild the C++ addon to get bbox diagnostics');
      }

      // Debug: confirm test is running
      // eslint-disable-next-line no-console
      console.log('[Braai Test] Running export logic...');

      // Debug: log result structure
      // eslint-disable-next-line no-console
      console.log('[Braai Test] split_by_bends result:', JSON.stringify(result, null, 2));

      // Export all panels and protrusions to JSON for inspection
      const outDir = path.resolve(__dirname, '../../exports/braai_panels');
      // Debug: log output directory
      // eslint-disable-next-line no-console
      console.log('[Braai Test] Output directory:', outDir);
      if (!fs.existsSync(outDir)) {
        fs.mkdirSync(outDir, { recursive: true });
        // eslint-disable-next-line no-console
        console.log('[Braai Test] Created output directory');
      }

      // Write the main result object
      fs.writeFileSync(path.join(outDir, 'split_by_bends_result.json'), JSON.stringify(result, null, 2));
      // eslint-disable-next-line no-console
      console.log('[Braai Test] Wrote split_by_bends_result.json');

      // Write each panel geometry to a separate file (if available)
      if (result.panel_geometries && Array.isArray(result.panel_geometries)) {
        result.panel_geometries.forEach((geom: any, idx: number) => {
          fs.writeFileSync(
            path.join(outDir, `panel_${idx + 1}.json`),
            JSON.stringify(geom, null, 2)
          );
          // eslint-disable-next-line no-console
          console.log(`[Braai Test] Wrote panel_${idx + 1}.json`);
        });
      } else if (result.panel_ids && Array.isArray(result.panel_ids)) {
        // If only IDs are available, write them as a list
        fs.writeFileSync(
          path.join(outDir, 'panel_ids.json'),
          JSON.stringify(result.panel_ids, null, 2)
        );
        // eslint-disable-next-line no-console
        console.log('[Braai Test] Wrote panel_ids.json');
      }

      // Optionally export protrusions if present
      if (result.protrusion_geometries && Array.isArray(result.protrusion_geometries)) {
        result.protrusion_geometries.forEach((geom: any, idx: number) => {
          fs.writeFileSync(
            path.join(outDir, `protrusion_${idx + 1}.json`),
            JSON.stringify(geom, null, 2)
          );
          // eslint-disable-next-line no-console
          console.log(`[Braai Test] Wrote protrusion_${idx + 1}.json`);
        });
      } else if (result.protrusion_ids && Array.isArray(result.protrusion_ids)) {
        fs.writeFileSync(
          path.join(outDir, 'protrusion_ids.json'),
          JSON.stringify(result.protrusion_ids, null, 2)
        );
        // eslint-disable-next-line no-console
        console.log('[Braai Test] Wrote protrusion_ids.json');
      }
    });
*/
  // The flange tabs on cube_with_flanges are all classified as "outer" faces by the
  // centroid-based isOuter heuristic, so detectProtrusions (which only scans for
  // non-outer faces adjacent to outer faces) returns 0 protrusions. Under tight local
  // oriented-box cutting, the flanges are isolated as their own clean flat panels
  // rather than being over-captured and absorbed into parent slabs, resulting in
  // exactly 10 clean panels (6 parent walls + 4 flanges) with 0 bends.
  it('cube with flanges → thin_solid mode, 10 clean isolated panels (6 walls + 4 flanges)', async () => {
    if (!addonAvailable) return;

    const fixturePath = findFixture('cube_with_flanges.stp');
    if (!fixturePath) {
      console.warn('cube_with_flanges.stp not found — run generate_fixtures first');
      return;
    }

    const config = loadConfig(configPath);

    const clean = await dispatchTool('clean_geometry', { file_path: fixturePath }, config) as any;
    expect(clean.solid_id).toBeDefined();

    const result = await dispatchTool('split_body_by_bends', {
      part_id: clean.solid_id,
      angle_threshold_deg: 45,
      max_thickness_mm: 5.0,
    }, config) as any;

    expect(result.detected_mode).toBe('thin_solid');
    expect(result.panel_count).toBe(10);
    expect(result.protrusion_count).toBe(0);
    expect(result.panel_ids).toHaveLength(10);
    expect(result.rollback_token).toBeDefined();
  });

  // ── Feature 008-splits-by-bends-viewport-alignment ───────────────────────────

  it('cauldron.step → decomposes correctly into flat trapezoidal panels without isolated triangles', async () => {
    if (!addonAvailable) return;

    const fixturePath = findFixture('cauldron.step');
    if (!fixturePath) {
      console.warn('cauldron.step not found');
      return;
    }

    const config = loadConfig(configPath);
    const clean = await dispatchTool('clean_geometry', { file_path: fixturePath }, config) as any;
    expect(clean.solid_id).toBeDefined();

    const result = await dispatchTool('split_body_by_bends', {
      part_id: clean.solid_id,
      angle_threshold_deg: 0.5,
      max_thickness_mm: 5.0,
    }, config) as any;

    expect(result.detected_mode).toBe('surface');
    expect(result.panel_count).toBe(82);
    expect(result.panel_ids.length).toBe(result.panel_count);
    expect(result.shape_history).toBeDefined();
  });

  it('cauldron.step → center_and_align_body translates centroid to [0,0,0] and aligns dominant axis', async () => {
    if (!addonAvailable) return;

    const fixturePath = findFixture('cauldron.step');
    if (!fixturePath) {
      console.warn('cauldron.step not found');
      return;
    }

    const config = loadConfig(configPath);
    const clean = await dispatchTool('clean_geometry', { file_path: fixturePath }, config) as any;
    expect(clean.solid_id).toBeDefined();

    const transaction = await dispatchTool('begin_transaction', { label: 'align_cauldron' }, config) as any;
    expect(transaction.transaction_id).toBeDefined();

    const aligned = await dispatchTool('center_and_align_body', {
      part_id: clean.solid_id,
      transaction_id: transaction.transaction_id,
    }, config) as any;

    expect(aligned.solid_id).toBeDefined();
    expect(Math.abs(aligned.centroid[0])).toBeLessThan(0.001);
    expect(Math.abs(aligned.centroid[1])).toBeLessThan(0.001);
    expect(Math.abs(aligned.centroid[2])).toBeLessThan(0.001);
    expect(aligned.rotation_matrix).toHaveLength(9);

    await dispatchTool('rollback_transaction', { transaction_id: transaction.transaction_id }, config);
  });

  it('cauldron adjacent split panels → merge_bodies_with_bend watertight fuse', async () => {
    if (!addonAvailable) return;

    const fixturePath = findFixture('cauldron.step');
    if (!fixturePath) {
      console.warn('cauldron.step not found');
      return;
    }

    const config = loadConfig(configPath);
    const clean = await dispatchTool('clean_geometry', { file_path: fixturePath }, config) as any;
    expect(clean.solid_id).toBeDefined();

    const transaction = await dispatchTool('begin_transaction', { label: 'merge_cauldron' }, config) as any;
    expect(transaction.transaction_id).toBeDefined();

    try {
      const split = await dispatchTool('split_body_by_bends', {
        part_id: clean.solid_id,
        angle_threshold_deg: 0.5,
        max_thickness_mm: 5.0,
        transaction_id: transaction.transaction_id,
      }, config) as any;

      expect(split.panel_count).toBeGreaterThanOrEqual(21);

      // Merging two non-adjacent split panels (disjoint in distance) correctly
      // fails with GE_MERGE_DISCONNECTED under any active check.
      try {
        await dispatchTool('merge_bodies_with_bend', {
          part_a_id: split.panel_ids[0],
          part_b_id: split.panel_ids[20],
          target_edges: ['all'],
          bend_radius: 2.0,
          transaction_id: transaction.transaction_id,
        }, config);
        expect(true).toBe(false); // must throw
      } catch (err: any) {
        expect(['GE_MERGE_DISCONNECTED', 'GE_MERGE_EDGE_MISALIGNED']).toContain(err?.code);
      }
    } finally {
      await dispatchTool('rollback_transaction', { transaction_id: transaction.transaction_id }, config);
    }
  });

  // ── merge_bodies_with_bend at various dihedral angles ────────────────────────
  //
  // Each fixture is an L-bracket: two 100×200×1.5 mm panels joined at a sharp
  // bend of the stated dihedral angle.  split_body_by_bends (with threshold just
  // below the bend angle) should return exactly 2 panels; merge_bodies_with_bend
  // should fuse them back into a single watertight shell.
  //
  // The fixtures are generated by generate_fixtures.cc (genAngleBracket).

  for (const { angleDeg, threshold } of [
    { angleDeg: 15, threshold: 10 },
    { angleDeg: 30, threshold: 20 },
    { angleDeg: 45, threshold: 35 },
  ]) {
    it(`angle_bracket_${angleDeg}deg: split → 2 panels, merge_bodies_with_bend succeeds`, async () => {
      if (!addonAvailable) return;

      const fixtureName = `angle_bracket_${angleDeg}deg.stp`;
      const fixturePath = findFixture(fixtureName);
      if (!fixturePath) {
        console.warn(`${fixtureName} not found — run generate_fixtures first`);
        return;
      }

      const config = loadConfig(configPath);

      const clean = await dispatchTool('clean_geometry', { file_path: fixturePath }, config) as any;
      expect(clean.solid_id).toBeDefined();

      const split = await dispatchTool('split_body_by_bends', {
        part_id: clean.solid_id,
        angle_threshold_deg: threshold,
        max_thickness_mm: 5.0,
      }, config) as any;

      expect(split.detected_mode).toBe('thin_solid');
      expect(split.panel_count).toBe(2);
      expect(split.panel_ids).toHaveLength(2);

      const [panelA, panelB] = split.panel_ids as [string, string];

      const merged = await dispatchTool('merge_bodies_with_bend', {
        part_a_id: panelA,
        part_b_id: panelB,
        target_edges: ['all'],
        bend_radius: 1.0,
      }, config) as any;

      expect(merged.merged_shell_id).toBeDefined();
      expect(merged.graphs_merged).toBe(true);
      // merged_part_id is stable and equals the caller's part_a_id
      expect(merged.merged_part_id).toBe(panelA);
      expect(merged.rollback_token).toBeDefined();
    });
  }

  it('cauldron.step → remove_protrusions loop_traversal vs legacy_volumetric', async () => {
    if (!addonAvailable) return;

    const fixturePath = findFixture('cauldron.step');
    if (!fixturePath) {
      console.warn('cauldron.step not found');
      return;
    }

    const config = loadConfig(configPath);
    const clean = await dispatchTool('clean_geometry', { file_path: fixturePath }, config) as any;
    expect(clean.solid_id).toBeDefined();

    const transaction = await dispatchTool('begin_transaction', { label: 'remove_prot_cauldron' }, config) as any;
    expect(transaction.transaction_id).toBeDefined();

    try {
      const resultLoop = await dispatchTool('remove_protrusions', {
        part_id: clean.solid_id,
        algorithm: 'loop_traversal',
        transaction_id: transaction.transaction_id,
      }, config) as any;

      expect(resultLoop.cleaned_part_id).toBeDefined();
    } finally {
      // Rollback the first transaction before executing another remove_protrusions on clean.solid_id,
      // so we don't hit active transaction collisions in subsequent tests.
      await dispatchTool('rollback_transaction', { transaction_id: transaction.transaction_id }, config);
    }

    const transaction2 = await dispatchTool('begin_transaction', { label: 'remove_prot_cauldron_legacy' }, config) as any;
    expect(transaction2.transaction_id).toBeDefined();

    try {
      const resultLegacy = await dispatchTool('remove_protrusions', {
        part_id: clean.solid_id,
        algorithm: 'legacy_volumetric',
        transaction_id: transaction2.transaction_id,
      }, config) as any;

      expect(resultLegacy.cleaned_part_id).toBeDefined();
    } finally {
      await dispatchTool('rollback_transaction', { transaction_id: transaction2.transaction_id }, config);
    }
  });
  
});
