/**
 * Integration tests for split_body_by_bends using real STEP fixtures.
 *
 * Requires:
 *   1. A built geometry_addon.node (cpp/build/Release/ or cpp/build-vcpkg/Debug/)
 *   2. STEP fixtures generated by `generate_fixtures` (cpp/tests/fixtures/)
 *
 * Tests are skipped silently when the addon or fixtures are absent.
 */

import { describe, expect, it, beforeAll } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';

import { dispatchTool } from '../../src/mcp/tools';
import { loadConfig } from '../../src/config/loader';

// ─── Addon detection ──────────────────────────────────────────────────────────

function findAddonPath(): string | undefined {
  const candidates = [
    path.resolve(__dirname, '../../../cpp/build-vcpkg/Debug/geometry_addon.node'),
    path.resolve(__dirname, '../../../cpp/build/Debug/geometry_addon.node'),
    path.resolve(__dirname, '../../../cpp/build/Release/geometry_addon.node'),
  ];
  return candidates.find(p => fs.existsSync(p));
}

function findFixture(filename: string): string | undefined {
  const fixturesDir = path.resolve(__dirname, '../../../cpp/tests/fixtures');
  const fp = path.join(fixturesDir, filename);
  return fs.existsSync(fp) ? fp : undefined;
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('split_body_by_bends integration', () => {
  let addonAvailable = false;
  const configPath = path.resolve(__dirname, '../../config/config.yaml');

  beforeAll(() => {
    const addonPath = findAddonPath();
    if (addonPath) {
      process.env['GEOMETRY_ADDON_PATH'] = addonPath;
      addonAvailable = true;
    }
  });

  it('hollow cube → thin_solid mode, 6 panels, 0 protrusions', async () => {
    if (!addonAvailable) return;

    const fixturePath = findFixture('hollow_cube.stp');
    if (!fixturePath) {
      console.warn('hollow_cube.stp not found — run generate_fixtures first');
      return;
    }

    const config = loadConfig(configPath);

    const clean = await dispatchTool('clean_geometry', { file_path: fixturePath }, config) as any;
    expect(clean.solid_id).toBeDefined();

    const result = await dispatchTool('split_body_by_bends', {
      part_id: clean.solid_id,
      angle_threshold_deg: 45,
      max_thickness_mm: 5.0,
    }, config) as any;

    expect(result.detected_mode).toBe('thin_solid');
    expect(result.panel_count).toBe(6);
    expect(result.protrusion_count).toBe(0);
    expect(result.panel_ids).toHaveLength(6);
    expect(result.rollback_token).toBeDefined();
  });

  // The flange tabs on cube_with_flanges are all classified as "outer" faces by the
  // centroid-based isOuter heuristic, so detectProtrusions (which only scans for
  // non-outer faces adjacent to outer faces) returns 0 protrusions. The flanges are
  // instead absorbed into the 6 panel slabs — each flange outer face finds the same
  // inner cutting plane as its parent wall, so the panel slab includes the flange.
  it('cube with flanges → thin_solid mode, 6 panels (flanges absorbed into slabs)', async () => {
    if (!addonAvailable) return;

    const fixturePath = findFixture('cube_with_flanges.stp');
    if (!fixturePath) {
      console.warn('cube_with_flanges.stp not found — run generate_fixtures first');
      return;
    }

    const config = loadConfig(configPath);

    const clean = await dispatchTool('clean_geometry', { file_path: fixturePath }, config) as any;
    expect(clean.solid_id).toBeDefined();

    const result = await dispatchTool('split_body_by_bends', {
      part_id: clean.solid_id,
      angle_threshold_deg: 45,
      max_thickness_mm: 5.0,
    }, config) as any;

    expect(result.detected_mode).toBe('thin_solid');
    expect(result.panel_count).toBe(6);
    expect(result.protrusion_count).toBe(0);
    expect(result.panel_ids).toHaveLength(6);
    expect(result.rollback_token).toBeDefined();
  });
});
