/**
 * v2 driver for the core correctness suite's C22 polygon-closure family
 * (rebuild/suite/cases/T2, generated by rebuild/suite/generator/closure_family.mjs)
 * — Phase 5 Slice 1.
 *
 * Unlike suite_driver_v1 (which has no graph-authoring path and must emulate
 * closure via import/transform/merge), v2 authors the case directly as graph
 * rows through the real v2 tool surface (create_part, create_node) and reads
 * the result back through evaluate-client.ts — exercising exactly the path a
 * real MCP client would use.
 *
 * Construction is calibrated against a direct Evaluate()-level investigation
 * test (cpp/tests/manufacturing_graph_evaluator_test.cc, "sharp (r=0) N=3
 * closure — mountain matches..."), confirmed with zero NAPI/TS involved:
 *   - "sharp" (r=0) strips are ALWAYS authored as mountain folds
 *     (angleDeg = +bendDeg). A valley fold at r=0 self-closes correctly but
 *     carries a real thicknessMm-scale pivot offset even at zero radius (real
 *     sheet-metal physics, not a bug) — so negating angleDeg for "down" would
 *     never match the suite's zero-thickness-idealized oracle.
 *   - bendDir "down" is a 180-degree-about-X WORLD ANCHOR (not Y — an
 *     N=3-only coincidence made Y look right before N=4 disproved it: Y
 *     negates X and Z together, corrupting any checkpoint with a nonzero X
 *     component, which N=3's single checkpoint never has) on top of the same
 *     mountain construction; "up" uses an identity anchor. X-about mirroring
 *     also negates the flat-pattern's own width (Y) axis, so the "width-side"
 *     query corner must be queried at LOCAL y=-widthMm (not +widthMm) to land
 *     at the correct world position — see WIDTH_SIGN below. Verified exact
 *     (<1e-9mm) against N=4's three checkpoints, which discriminate on both
 *     X and Z simultaneously.
 *
 * Gated behind SUITE_V2_DRIVER=1 — needs the native binding built:
 *
 *   SUITE_V2_DRIVER=1 npx vitest run tests/integration/suite_driver_v2
 *
 * Pose sweep (28 of the 42 cases use pose.rotDeg=30 or 137, some with a
 * nonzero offsetMm too): rebuild/suite/schema.md rule 3 is the authoritative
 * source — "Expected coordinates are panel-0-frame; drivers map to world
 * coordinates via the implementation's own reported frame — so a pose sweep
 * changes nothing in the case's oracles (invariance by construction)." This
 * driver builds its OWN pose transform (rotate about world Z by rotDeg, then
 * translate by offsetMm — an arbitrary but self-consistent choice; rule 3
 * guarantees invariance under ANY consistent choice, not just this one) and
 * composes it as an EXTRA outermost layer on top of the up/down anchor
 * (poseTransform.Compose(canonicalAnchor) — apply canonical first, pose
 * second). The raw JSON checkpoint values are transformed through that SAME
 * poseTransform before comparison (never through the full anchor — bendDir's
 * mirror is already baked into the raw checkpoint's own sign, confirmed by
 * the rot000 subset; re-applying it here would double it). Verified exact
 * (0.000000mm) against N=4 for every combination (up/down x rot030/rot137,
 * i.e. rotation alone and rotation+offset together) via a throwaway NAPI
 * probe before being written here — N=3 was deliberately avoided as the
 * calibration target after it masked the earlier up/down mirror-axis bug.
 */
import { describe, expect, it } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';

import { GraphStore } from '../../src/v2/graph/store';
import { dispatchGraphTool } from '../../src/v2/tools/graph';
import { evaluatePart, constructPart } from '../../src/v2/graph/evaluate-client';
import type { NapiTransform3, NapiRegionPanelLayout } from '../../src/geometry/types';

const ENABLED = process.env.SUITE_V2_DRIVER === '1';
const d = ENABLED ? describe : describe.skip;

const SUITE_DIR = path.resolve(__dirname, '../../../rebuild/suite');

interface Profile {
  closureMm: number;
}
const profiles: Record<string, Profile> = JSON.parse(
  fs.readFileSync(path.join(SUITE_DIR, 'profiles.json'), 'utf8'),
) as Record<string, Profile>;

interface Checkpoint {
  afterBend: number;
  endCorners: [number[], number[]];
}

interface SuiteCase {
  id: string;
  toleranceProfile: string;
  params: {
    N: number;
    bendDeg: number;
    segmentLenMm: number;
    widthMm: number;
    thicknessMm: number;
    bendDir: 'up' | 'down';
    variant: string;
  };
  ops: Array<{ op: string; pose?: { rotDeg: number; offsetMm: [number, number] } }>;
  oracles: [
    { type: 'closure'; checkpoints: Checkpoint[]; finalCoincidentWithStart: boolean },
    { type: 'structure'; solidCount: number; typedError: string | null },
  ];
}

function loadT2Cases(): SuiteCase[] {
  const dir = path.join(SUITE_DIR, 'cases', 'T2');
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')) as SuiteCase);
}

function casePose(c: SuiteCase): { rotDeg: number; offsetMm: [number, number] } {
  const author = c.ops.find((o) => o.op === 'author_strip');
  const pose = author?.pose;
  expect(pose, `${c.id} must have an author_strip.pose`).toBeDefined();
  return pose as { rotDeg: number; offsetMm: [number, number] };
}

// ─── Duplicated formulas (documented, matching manufacturing_graph_evaluator's
// own model — see cpp/tests/manufacturing_graph_evaluator_test.cc's
// TestPivotZOffset/TestBendAllowanceMm/TestClosureFarX for the reference this
// mirrors and why an independent duplicate here is correct, not a
// principle-III violation: this is test-oracle math, computed once at
// construction time to author correct graph rows, never read back by
// production code). BA=0 always in this suite (every T2 case is "sharp").

function pivotZOffset(angleDeg: number, radiusMm: number, thicknessMm: number): number {
  const isMountain = angleDeg >= 0;
  const rBottom = isMountain ? radiusMm : radiusMm + thicknessMm;
  return isMountain ? -rBottom : rBottom;
}

function applyPose(
  pose: NapiTransform3,
  p: { x: number; y: number; z: number },
): { x: number; y: number; z: number } {
  const r = pose.r;
  return {
    x: r[0] * p.x + r[1] * p.y + r[2] * p.z + pose.t[0],
    y: r[3] * p.x + r[4] * p.y + r[5] * p.z + pose.t[1],
    z: r[6] * p.x + r[7] * p.y + r[8] * p.z + pose.t[2],
  };
}

function dist3(
  a: { x: number; y: number; z: number },
  b: { x: number; y: number; z: number },
): number {
  return Math.hypot(a.x - b.x, a.y - b.y, a.z - b.z);
}

// ─── Transform3 composition (documented duplicate of Transform3::Compose's own
// contract — "A.Compose(B).Apply(p) == A.Apply(B.Apply(p)), apply B first" —
// needed here only to build the pose-sweep anchor from rotDeg/offsetMm and to
// map raw checkpoint values through it before comparison; never read back by
// production code, matching this file's other duplicated-formula precedent.

function composeTransform(outer: NapiTransform3, inner: NapiTransform3): NapiTransform3 {
  const A = outer.r;
  const B = inner.r;
  const r: NapiTransform3['r'] = [0, 0, 0, 0, 0, 0, 0, 0, 0];
  for (let i = 0; i < 3; i++) {
    for (let j = 0; j < 3; j++) {
      let sum = 0;
      for (let k = 0; k < 3; k++) sum += A[3 * i + k] * B[3 * k + j];
      r[3 * i + j] = sum;
    }
  }
  const bt = { x: inner.t[0], y: inner.t[1], z: inner.t[2] };
  const rotatedBt = {
    x: A[0] * bt.x + A[1] * bt.y + A[2] * bt.z,
    y: A[3] * bt.x + A[4] * bt.y + A[5] * bt.z,
    z: A[6] * bt.x + A[7] * bt.y + A[8] * bt.z,
  };
  const t: NapiTransform3['t'] = [
    rotatedBt.x + outer.t[0],
    rotatedBt.y + outer.t[1],
    rotatedBt.z + outer.t[2],
  ];
  return { r, t };
}

/** Rotation about world Z by degDeg (right-hand rule), zero translation. */
function rotationZAxis(deg: number): NapiTransform3 {
  const rad = (deg * Math.PI) / 180;
  const c = Math.cos(rad);
  const s = Math.sin(rad);
  return { r: [c, -s, 0, s, c, 0, 0, 0, 1], t: [0, 0, 0] };
}

function translationTransform(dx: number, dy: number, dz: number): NapiTransform3 {
  return { r: [1, 0, 0, 0, 1, 0, 0, 0, 1], t: [dx, dy, dz] };
}

/** The pose sweep's own extra transform — see file banner for why rotate-Z-
 * then-translate is an arbitrary but sufficient choice. */
function poseTransformOf(pose: { rotDeg: number; offsetMm: [number, number] }): NapiTransform3 {
  return composeTransform(
    translationTransform(pose.offsetMm[0], pose.offsetMm[1], 0),
    rotationZAxis(pose.rotDeg),
  );
}

function requirePanel(
  byId: Map<string, NapiRegionPanelLayout>,
  regionPanelId: string,
): NapiRegionPanelLayout {
  const panel = byId.get(regionPanelId);
  expect(panel, `region panel ${regionPanelId} must exist in the evaluated layout`).toBeDefined();
  return panel as NapiRegionPanelLayout;
}

const IDENTITY_ANCHOR: NapiTransform3 = { r: [1, 0, 0, 0, 1, 0, 0, 0, 1], t: [0, 0, 0] };
// 180 degrees about world X: (x,y,z) -> (x,-y,-z) — mirrors "up" into "down"
// while leaving the fold-plane (X,Z) heading's own X-component untouched
// (confirmed exact against N=4's checkpoints; see file banner for why the
// alternative, 180-about-Y, only looked correct for N=3 by coincidence).
const MIRROR_X_ANCHOR: NapiTransform3 = { r: [1, 0, 0, 0, -1, 0, 0, 0, -1], t: [0, 0, 0] };

/** Authors one case's full N-1-bend closed strip via the real v2 tool surface. */
function authorStrip(
  store: GraphStore,
  params: SuiteCase['params'],
  pose: { rotDeg: number; offsetMm: [number, number] },
): { partId: string; segRegionPanelIds: string[] } {
  const { N, bendDeg, segmentLenMm: L, widthMm, thicknessMm, bendDir } = params;
  const bendCount = N - 1;
  // BA=0 (sharp): totalLen = N*L, minus one thicknessMm closing setback so the
  // real "construct" solid doesn't self-intersect at the closing seam.
  const totalLen = N * L - thicknessMm;
  const canonicalAnchor = bendDir === 'down' ? MIRROR_X_ANCHOR : IDENTITY_ANCHOR;
  // Pose is an EXTRA outermost layer: apply the canonical (bendDir) anchor
  // first, the pose sweep's own transform second — see file banner.
  const anchor = composeTransform(poseTransformOf(pose), canonicalAnchor);

  const createPartResult = dispatchGraphTool(store, 'create_part', {
    name: `suite-${params.N}-${bendDir}`,
    outline: [
      { x: 0, y: 0 },
      { x: totalLen, y: 0 },
      { x: totalLen, y: widthMm },
      { x: 0, y: widthMm },
    ],
    thickness_mm: thicknessMm,
    anchor,
  }) as { part_id: string; root_region_panel_id: string };

  const partId = createPartResult.part_id;
  const segRegionPanelIds = [createPartResult.root_region_panel_id];
  let parentRegionPanelId = createPartResult.root_region_panel_id;

  const halfSpan = widthMm / 2 + widthMm; // generous hinge span, matches MakeStrip
  for (let i = 0; i < bendCount; i++) {
    const hx = (i + 1) * L; // BA=0: no zone-width term needed
    const createNodeResult = dispatchGraphTool(store, 'create_node', {
      kind: 'bend',
      part_id: partId,
      parent_region_panel_id: parentRegionPanelId,
      hinge_a: { x: hx, y: widthMm / 2 + halfSpan },
      hinge_b: { x: hx, y: widthMm / 2 - halfSpan },
      angle_deg: bendDeg, // always mountain — see file banner
      radius_mm: 0,
      k_factor: 0,
    }) as { bend_id: string; child_region_panel_id: string };
    parentRegionPanelId = createNodeResult.child_region_panel_id;
    segRegionPanelIds.push(parentRegionPanelId);
  }

  return { partId, segRegionPanelIds };
}

d('core correctness suite — v2 driver (C22 polygon closure)', () => {
  const cases = loadT2Cases();
  expect(cases.length).toBe(42);

  for (const c of cases) {
    it(c.id, () => {
      const budget = profiles[c.toleranceProfile].closureMm;
      const { N, bendDeg, segmentLenMm: L, widthMm, thicknessMm } = c.params;
      const pose = casePose(c);
      const poseTransform = poseTransformOf(pose);

      const store = new GraphStore();
      const { partId, segRegionPanelIds } = authorStrip(store, c.params, pose);

      // "construct" op — proxy for the structure oracle (solidCount:1,
      // typedError:null): constructPart's own ok/errorCode contract already
      // encodes exactly that pass/fail distinction.
      const constructResult = constructPart(store, partId);
      expect(constructResult.ok, constructResult.message).toBe(true);
      expect(constructResult.shellId).toBeTruthy();

      // "map_strip_ends" op / closure oracle — read the full evaluated layout
      // once; each seg_k's own pose already reflects exactly bends 0..k-1
      // (bend_k itself only affects seg_{k+1} onward), so every checkpoint
      // AND the final closure check come from this one evaluate() call.
      const evalResult = evaluatePart(store, partId);
      expect(evalResult.ok, evalResult.message).toBe(true);

      const byId = new Map<string, NapiRegionPanelLayout>(
        evalResult.panels.map((p) => [p.regionPanelId, p]),
      );
      const z = pivotZOffset(bendDeg, 0, thicknessMm);
      const farX = N * L; // BA=0: no closure correction needed for open checkpoints
      // MIRROR_X_ANCHOR negates the flat-pattern's own Y (width) axis, so the
      // width-side query must use LOCAL y=-widthMm for "down" to land at the
      // correct world position — see file banner.
      const widthSign = c.params.bendDir === 'down' ? -1 : 1;

      let worst = 0;
      for (const checkpoint of c.oracles[0].checkpoints) {
        const seg = requirePanel(byId, segRegionPanelIds[checkpoint.afterBend]);
        const got0 = applyPose(seg.pose, { x: farX, y: 0, z });
        const got1 = applyPose(seg.pose, { x: farX, y: widthSign * widthMm, z });
        // Raw checkpoint values are panel-0-frame (schema.md rule 3) — map
        // through this driver's OWN pose transform (not the full anchor:
        // bendDir's mirror is already baked into the raw value's own sign)
        // to get the expected WORLD position for this authoring's pose.
        const exp0 = applyPose(poseTransform, {
          x: checkpoint.endCorners[0][0],
          y: checkpoint.endCorners[0][1],
          z: checkpoint.endCorners[0][2],
        });
        const exp1 = applyPose(poseTransform, {
          x: checkpoint.endCorners[1][0],
          y: checkpoint.endCorners[1][1],
          z: checkpoint.endCorners[1][2],
        });
        worst = Math.max(worst, dist3(got0, exp0), dist3(got1, exp1));
      }

      if (c.oracles[0].finalCoincidentWithStart) {
        const seg0 = requirePanel(byId, segRegionPanelIds[0]);
        const segLast = requirePanel(byId, segRegionPanelIds[N - 1]);
        // closure-corrected farX: undoes the thicknessMm closing setback baked
        // into totalLen (see TestClosureFarX's own comment for why this is
        // mathematically exact regardless of that construction-only setback).
        const closureFarX = N * L - thicknessMm + thicknessMm;
        const start = applyPose(seg0.pose, { x: 0, y: 0, z });
        const end = applyPose(segLast.pose, { x: closureFarX, y: 0, z });
        worst = Math.max(worst, dist3(start, end));
      }

      console.log(
        `[suite:${c.id}] worst closure residual ${worst.toFixed(6)} mm (budget ${budget})`,
      );
      expect(worst).toBeLessThanOrEqual(budget);
    });
  }

  // Hand-authored smoke cases: closure_family.mjs never emits N<3 (there is
  // no "closure" to check below a triangle), so the slice goal's "single
  // panels & chains" language isn't otherwise exercised at N=1/N=2.
  it('smoke: N=1 no-bend part evaluates to a single identity-posed panel', () => {
    const store = new GraphStore();
    const createPartResult = dispatchGraphTool(store, 'create_part', {
      name: 'smoke-n1',
      outline: [
        { x: 0, y: 0 },
        { x: 100, y: 0 },
        { x: 100, y: 50 },
        { x: 0, y: 50 },
      ],
      thickness_mm: 1.0,
    }) as { part_id: string; root_region_panel_id: string };

    const evalResult = evaluatePart(store, createPartResult.part_id);
    expect(evalResult.ok, evalResult.message).toBe(true);
    expect(evalResult.panels).toHaveLength(1);
    expect(evalResult.bridges).toHaveLength(0);

    const panel = requirePanel(
      new Map(evalResult.panels.map((p) => [p.regionPanelId, p])),
      createPartResult.root_region_panel_id,
    );
    // Identity anchor, no bends: bottomFace is the outline embedded at z=0.
    const corner = applyPose(panel.pose, { x: 100, y: 50, z: 0 });
    expect(dist3(corner, { x: 100, y: 50, z: 0 })).toBeLessThan(1e-9);

    const constructResult = constructPart(store, createPartResult.part_id);
    expect(constructResult.ok, constructResult.message).toBe(true);
  });

  it('smoke: N=2 one-bend part folds to the expected 90-degree corner position', () => {
    const store = new GraphStore();
    const L = 60,
      widthMm = 40,
      thicknessMm = 1,
      bendDeg = 90;
    const createPartResult = dispatchGraphTool(store, 'create_part', {
      name: 'smoke-n2',
      outline: [
        { x: 0, y: 0 },
        { x: 2 * L, y: 0 },
        { x: 2 * L, y: widthMm },
        { x: 0, y: widthMm },
      ],
      thickness_mm: thicknessMm,
      anchor: IDENTITY_ANCHOR,
    }) as { part_id: string; root_region_panel_id: string };

    const createNodeResult = dispatchGraphTool(store, 'create_node', {
      kind: 'bend',
      part_id: createPartResult.part_id,
      parent_region_panel_id: createPartResult.root_region_panel_id,
      hinge_a: { x: L, y: widthMm + 50 },
      hinge_b: { x: L, y: -50 },
      angle_deg: bendDeg,
      radius_mm: 0,
      k_factor: 0,
    }) as { bend_id: string; child_region_panel_id: string };

    const evalResult = evaluatePart(store, createPartResult.part_id);
    expect(evalResult.ok, evalResult.message).toBe(true);
    expect(evalResult.panels).toHaveLength(2);
    expect(evalResult.bridges).toHaveLength(1);

    const byId = new Map(evalResult.panels.map((p) => [p.regionPanelId, p]));
    const seg1 = requirePanel(byId, createNodeResult.child_region_panel_id);
    const z = pivotZOffset(bendDeg, 0, thicknessMm);
    const got = applyPose(seg1.pose, { x: 2 * L, y: 0, z });
    // Sharp 90-degree mountain fold at the hinge (x=L): the far corner swings
    // from (2L,0,0) to (L,0,L) — a quarter-turn about the hinge line.
    const expected = { x: L, y: 0, z: L };
    expect(dist3(got, expected)).toBeLessThan(1e-6);

    const constructResult = constructPart(store, createPartResult.part_id);
    expect(constructResult.ok, constructResult.message).toBe(true);
  });
});
