/**
 * Manufacturing Graph error codes.
 * Extends the central ErrorCodes registry in ts/src/mcp/errors.ts.
 *
 * Spec: specs/009-manufacturing-graph/contracts/mcp-tools.md (error registry)
 * Task: T003
 */

// These are exported as string literals that match the keys added to ErrorCodes.
// The actual ErrorCodes object is updated in errors.ts.

export const GraphErrorCodes = {
  NODE_ID_ALREADY_EXISTS: 'NODE_ID_ALREADY_EXISTS',
  NODE_NOT_FOUND: 'NODE_NOT_FOUND',
  MANUFACTURING_GRAPH_CYCLE_DETECTED: 'MANUFACTURING_GRAPH_CYCLE_DETECTED',
  REMOVE_WOULD_ORPHAN_NODES: 'REMOVE_WOULD_ORPHAN_NODES',
  JOIN_EDGE_ALREADY_BOUND: 'JOIN_EDGE_ALREADY_BOUND',
  GRAPH_INTEGRITY_ERROR: 'GRAPH_INTEGRITY_ERROR',
  BOOTSTRAP_PARTIAL: 'BOOTSTRAP_PARTIAL',
  GRAPH_ALREADY_POPULATED: 'GRAPH_ALREADY_POPULATED',
  SOLVE_FAILED: 'SOLVE_FAILED',
  GEOMETRY_STALE: 'GEOMETRY_STALE',
  DRC_BEND_RADIUS_VIOLATION: 'DRC_BEND_RADIUS_VIOLATION',
  DRC_MIN_FLANGE_WIDTH_VIOLATION: 'DRC_MIN_FLANGE_WIDTH_VIOLATION',
  DRC_FOLDABILITY_VIOLATION: 'DRC_FOLDABILITY_VIOLATION',
  DRC_FOLDABILITY_UNCERTAIN: 'DRC_FOLDABILITY_UNCERTAIN',
  DRC_CUT_IN_BEND_ZONE: 'DRC_CUT_IN_BEND_ZONE',
  CUT_PROFILE_OUT_OF_BOUNDS: 'CUT_PROFILE_OUT_OF_BOUNDS',
  CUT_OVERLAP: 'CUT_OVERLAP',
  CUT_INVALID_PROFILE: 'CUT_INVALID_PROFILE',
} as const;

export type GraphErrorCode = (typeof GraphErrorCodes)[keyof typeof GraphErrorCodes];
